platform :ios, '9.3'
target 'ViroSample' do
  use_frameworks!
  pod 'ViroReact', :path => '../node_modules/phantom-react/ios/'
  pod 'ViroKit', :path => '../node_modules/phantom-react/ios/dist/ViroRenderer/'
end
