platform :ios, '10.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

def common
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  
  use_flipper!
end

target 'ViroReact' do
  common
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'ViroReact_static_lib' do
  common
end


target 'ViroReact_release_tests' do
end
