# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.66.2"

require 'Fileutils.rb'

default_platform :android

platform :android do
  before_all do
    BUILD_INTERMEDIATES = "/var/tmp/build_intermediates/"
    GIT_BRANCH = git_branch
  end

  def on_error(exception)
       slack(
           message: ":thunder_cloud_and_rain: Build Pipeline failed!",
           success: false,
           default_payloads: [], #Pass an empty array to suppress all the default payloads.
           payload: {
            "Git Repository:" =>  "phantom-react/#{GIT_BRANCH}",
            "Fastlane Lane:" => ENV["FASTLANE_LANE_NAME"],
            "Exception:" => "```#{exception}```"
           },
           use_webhook_configured_username_and_icon: true
       )
  end

  lane :save_git_log do
    begin
      sh("echo \"\n\nphantom-react/#{GIT_BRANCH}\n\" >> #{BUILD_INTERMEDIATES}s3_artifacts/git_log.txt")
      sh("git log #{GIT_BRANCH} --no-walk >> #{BUILD_INTERMEDIATES}s3_artifacts/git_log.txt")
    rescue => exception
           on_error(exception)
    end
  end

  lane :gradle_clean_bridge do
    begin
      gradle(task: "clean")
      sh("rm ../phantom_renderer/phantom_renderer-release.aar") # just to make sure
    rescue => exception
           on_error(exception)
    end
  end
  
  lane :phantom_react_bridge_aar do
    begin
      sh("cp #{BUILD_INTERMEDIATES}phantomreact_aar/phantom_renderer-release.aar ../phantom_renderer/")
    rescue => exception
           on_error(exception)
    end
  end
  
  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

# More information about multiple platforms in fastlane: https://docs.fastlane.tools/advanced/#control-configuration-by-lane-and-by-platform
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics
